development:
  adapter: postgresql
  database: scawy_m_development
  host: localhost
  username: jpoz
  password:

test:
  adapter: mysql
  database: scawy_production
  username: scawy
  password: XXX
  host: dataload.scawymonstur.com

production:
  adapter: mysql
  database: scawy_production
  username: scawy
  password: XXX
  host: dataload.scawymonstur.com